import {
  Injectable,
  NotFoundException,
  ForbiddenException,
  ConflictException,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { UpdateWorkspaceInvitationDto } from './dto/update-invitation.dto';
// Importing exact Enums generated by your Prisma schema
import {
  WorkspaceInvitationStatus,
  WorkspaceMemberRole,
} from '../generated/prisma/client';

@Injectable()
export class InvitationsService {
  constructor(private readonly prisma: PrismaService) {}

  async findAll(userId: string) {
    // The `where` clause filters invitations for the current user that are still pending.
    // The `include` clause fetches related workspace and inviter details,
    // but only the fields necessary for the frontend to display an invitation card
    // (workspace name, inviter's full name and username).
    return await this.prisma.workspaceInvitation.findMany({
      where: {
        inviteeId: userId,
        status: WorkspaceInvitationStatus.PENDING,
      },
      include: {
        workspace: {
          select: { name: true },
        },
        inviter: {
          select: { fullName: true, username: true },
        },
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  async update(
    userId: string,
    invitationId: string,
    updateDto: UpdateWorkspaceInvitationDto,
  ) {
    // Validate the invitation exists, belongs to the user, and is still pending.
    const invitation = await this.prisma.workspaceInvitation.findUnique({
      where: { id: invitationId },
    });

    if (!invitation) {
      throw new NotFoundException('Invitation not found');
    }

    if (invitation.inviteeId !== userId) {
      throw new ForbiddenException('This invitation does not belong to you');
    }

    if (invitation.status !== WorkspaceInvitationStatus.PENDING) {
      throw new ConflictException(
        'This invitation has already been responded to',
      );
    }

    // Prisma Interactive Transaction.
    // This ensures that if the user accepts the invitation, both the invitation status update
    // and the creation of the workspace membership happen atomically.
    // If the action is 'accept', but the membership creation fails for any reason, the entire transaction will roll back,
    // leaving the invitation status unchanged (still pending), which is a safe and consistent state.
    const result = await this.prisma.$transaction(async (tx) => {
      const newStatus =
        updateDto.action === 'accept'
          ? WorkspaceInvitationStatus.ACCEPTED
          : WorkspaceInvitationStatus.DECLINED;

      // Update the invitation status
      const updatedInvitation = await tx.workspaceInvitation.update({
        where: { id: invitationId },
        data: {
          status: newStatus,
          respondedAt: new Date(),
        },
      });

      // If accepted, create the membership
      if (newStatus === WorkspaceInvitationStatus.ACCEPTED) {
        // Map the WorkspaceInvitationRole Enum to the WorkspaceMemberRole Enum securely
        const targetRole =
          invitation.role === 'ADMIN'
            ? WorkspaceMemberRole.ADMIN
            : WorkspaceMemberRole.MEMBER;

        await tx.workspaceMember.create({
          data: {
            workspaceId: invitation.workspaceId,
            userId: userId,
            role: targetRole,
          },
        });
      }

      return updatedInvitation;
    });

    // TODO: If updateDto.action === 'accept', emit WS 'member_joined' to 'workspace:{wsId}'.

    // Mapeamento explícito para garantir o contrato da API
    return {
      id: result.id,
      workspaceId: result.workspaceId,
      inviterId: result.inviterId,
      inviteeEmail: result.inviteeEmail,
      role: result.role.toLowerCase(),
      status: result.status.toLowerCase(),
      createdAt: result.createdAt.toISOString(),
    };
  }
}
