services:
  db:
    image: postgres:15-alpine
    container_name: transcendence_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: transcendence_user
      POSTGRES_PASSWORD: transcendence_password
      POSTGRES_DB: transcendence_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    command: sh -c "npx prisma generate && sleep 3 && npx prisma db push && npm run start:dev"
    container_name: transcendence_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://transcendence_user:transcendence_password@db:5432/transcendence_db?schema=public"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: transcendence_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: "http://localhost:3000"
    depends_on:
      - backend

volumes:
  pgdata:
